setwd('/Users/hinagandhi/Desktop')
Hello<-read.csv("dataset_new.csv")
View(Hello)
library(xts)
Hello<-xts(order.by=as.Date(Hello[,1], "%m/%d/%Y"))
install.packages("astsa")
library(astsa)
names(Hello)
Hello<- subset(Hello, select=c(1,6:20))
#plot(Boston1$GDP, xlab="Quaterly", ylab="Deviation", main="Global Temperature Deviations, 1947-2016")
acf2(Hello$GDP)
acf2(Hello$PPI)
acf2(Hello$CPI)
acf2(Hello$Population)
acf2(Hello$Import)
acf2(Hello$Export)
acf2(Hello$M2)
acf2(Hello$Unemployment.Rate)
acf2(Hello$Purchase.Power.Parity)
acf2(Boston1$Inflation.Rate)
acf2(Hello$percent_change_gdp)
acf2(Hello$Total.Non.Farm.Payrolls)
acf2(Hello$Real.Manufacturing.Trade.Industries)
acf2(Hello$Real.Personal.Income)
acf2(Hello$Industrial.Production)
# using sarima model
setwd('/users/hinagandhi/desktop')
arima <- read.csv("dataset_new.csv")
ts.data <- NULL
ts.data <- ts(arima$GDP,frequency=4,start=c(1947,1))
plot(ts.data)
data.train = window(ts.data, start=c(1947,1), end= c(2010,12))
plot(data.train)
data.test = window(ts.data, start=c(2011,1))
plot(data.test)
library(forecast)
arima1 = auto.arima(data.train,trace=TRUE, test="kpss", ic="aic")
summary(arima1)
confint(arima1) 
plot.ts(arima1$residuals)
Box.test(arima1$residuals,lag=20,type="Ljung-Box")
acf(arima1$residuals^2, lag.max=24, main="ACF of the Model")
Box.test(arima1$residuals^2, lag=20, type="Ljung-Box")
library(tseries)
jarque.bera.test(arima1$residuals)

arima1.forecast = forecast.Arima(arima1, h=100)
arima1.forecast 
plot(arima1.forecast, xlab="Quartes", ylab="GDP")
install.packages("TSPred")
library(TSPred)
plotarimapred(data.test,arima1, xlim=c(2011, 2016), range.percent = .05)
accuracy(arima1.forecast,data.test)